#!/usr/bin/perl
# flexget-announced - daemon that announces new TV episodes

use strict;
use Proc::Daemon;
use App::Daemon qw(daemonize);

my $notifier = 'stumpish echo';
my $flexlog = "$ENV{HOME}/.flexget.log";
my $newEp = "";

print "Daemonizing, bye...\n";
daemonize();
while(1) {
  open(FLEX, "<", $flexlog) or die "$!\n";
  my @records = <FLEX>;
  close(FLEX);
  my @episodes;
  foreach my $record(@records) {
    next unless($record =~ /Downloading:/);
    $record =~ s/(?:\w+\s+){2}\w+:\s//;
    push(@episodes, $record) if $record =~ /(S[0-9]+)?(E[0-9]+)?(TV)/;
  }
  if($newEp ne @episodes[@episodes-1]) {
    $newEp = @episodes[@episodes-1];
    &notify($newEp);
  }

  sleep 300;
}

sub notify {
  my $toSend = shift;
  system("$notifier $toSend");
}
